### ISSUE TITLE
copy of literal array is not made when it is passed as argument to a non-const qualified formal parameter

### ISSUE THREAD

**Issue by YashasSamaga** [pawn-lang/compiler#276]
A copy of a literal array is not made on the heap before passing it to a function as an argument to a non-const qualified formal parameter. The changes made to the argument modify the array literal (this shouldn't be happening).

## Example:

The following snippet highlights the issue:

```
#include <a_samp>
f(arr[]) {
    printf("%s", arr);
    arr[3] = 'Z';
}
wrapper() {
    f("ABCDEFGHIK");
}
main () {
  wrapper();
  wrapper();
}
```

produces

```

ABCDEFGHIK
ABCZEFGHIK
```

Most people would expect "ABCDEFGHIK" to be passed in both the function calls. However, it does not. The compiler pushes the address of the literal array on to the stack and the function modifies the literal array. These changes are wrongly retained for future function calls.

## What could be done?

A copy of the literal array has to be made on the heap while passing it as an argument to a *non-const qualified* formal parameter. This will ensure that any changes to the array will not be reflected in the future function calls (which is intended).

In case the formal parameter is *const qualified*, then a copy wouldn't be needed as the function guarantees that it will not modify the literal array.

## Issues to be considered

- could break scripts which rely on the bug

- could add unnecessary performance cost to poorly written scripts (functions which are not const-correct, i.e: an array parameter which is not modified is not marked as const; this leads to unnecessary copying of the literal array on the heap)

More issues pointed out by Y_Less (https://github.com/pawn-lang/compiler/issues/276#issuecomment-361589014):

- SAMP natives are not const correct 

- Adding a warning for unmodified non-const arrays will introduce new warnings in legacy code.

-   How would this be controlled for vararg functions? What is the correct behaviour for passing `"hi"` to `F(...)`. The `...` simply cannot be declared `const` because not all the parameters may be constant, and there's no real way to determine which parameters are written to or not. Do you add the overhead of a copy to every string literal on the off-chance it is written to?

- Are there any demonstrable bugs changing this behaviour would have prevented?

**Comment by Y-Less** [comment]
More issues:

* Adding a warning for unmodified non-const arrays will introduce new warnings in legacy code.

* How would this be controlled for vararg functions?  What is the correct behaviour for passing `"hi"` to `F(...)`.  The `...` simply cannot be declared `const` because not all the parameters may be constant, and there's no real way to determine which parameters are written to or not.  Do you add the overhead of a copy to every string literal on the off-chance it is written to?

* Are there any demonstrable bugs changing this behaviour would have prevented?

**Comment by samphunter** [comment]
```
When you are working with strings, or arrays in
general, note that pawn always passes arrays by reference. It does this to
conserve memory and to increase performance
```
- According to PAWN language guide, this is correct behavior.

**Comment by YashasSamaga** [comment]
In the context of that paragraph in the PAWN Language Guide, the array being passed is not a literal. Users expect the array to be passed as reference.

However, in case of literals, I believe (at least me) that these supposedly *constant* literals should not be modified.

In fact, if you try to modify a string literal on a C++ compiler, you will mostly get a segmentation fault (because the literals end up in read-only data segment and this section is write-protected). But PAWN is not C++.

**Comment by Y-Less** [comment]
In retrospect I don't think adding warnings to legacy code is too terrible, since it will force people to actually update (assuming they updated the compiler). However, that doesn't answer the varargs question.

**Comment by samphunter** [comment]
@YashasSamaga right, but that should be fixed with a warning as Y_Less saied, not with copying data to prevent the modification.

@Y-Less agreed. It would also help if it was a new warning, so that it could be disabled by anyone not wanting to bother with fixing legacy codebases.

As for the vararg, I think we should just accept it is not possible to fix that. Making a copy would be terrible for performance in calls to functions such as format. We could allow const added to `...` that would affect all arrays passed to it. That would however not solve the problem of functions, such as CallLocalFunction, where you may want some constant strings and some, that are not.

The only way to fix this I can think of is enforcing the read-only property in the abstract machine, not in pawn itself. Even then, that does not solve natives.

**Comment by YashasSamaga** [comment]
@samphunter adding a warning does not fix the problem I stated; I pressume @Y-Less meant the warning which suggests adding `const` qualifier to arrays parameters when they are not modified.

It just makes people write const-correct code which would be be EXTREMELY useful if my suggestion was implemented because it would point out where the scripter could prevent costly copies.

**Comment by YashasSamaga** [comment]
> could break scripts which rely on the bug

There probably aren't many scripts which abuse this bug. If there are some, then it's bad code and they should update it.

##

> could add unnecessary performance cost to poorly written scripts (functions which are not const-correct, i.e: an array parameter which is not modified is not marked as const; this leads to unnecessary copying of the literal array on the heap)

can be prevented by writing const-correct code.

With the help of the warning 214 (`possibly a const array argument was intended`), const-correct code can be written.

## 
> SAMP natives are not const correct

I don't think anything can be done apart from modifying the includes itself. 

## 
> Adding a warning for unmodified non-const arrays will introduce new warnings in legacy code.

This would promote people to fix bad code. It suspect it won't take long for popular libraries to go const-correct.

## 
> How would this be controlled for vararg functions? What is the correct behaviour for passing "hi" to F(...). The ... simply cannot be declared const because not all the parameters may be constant, and there's no real way to determine which parameters are written to or not. Do you add the overhead of a copy to every string literal on the off-chance it is written to?

All variable arguments to variadic functions will be passed as reference. By that, we assume that all arguments are `const`. It is up to the person who writes such a function to ensure that modifications to the arguments are minimized. In many cases, the modifications done to the arguments can be undone before returning (a common example would be adding a NULL character to truncate a string).

##

> Are there any demonstrable bugs changing this behaviour would have prevented?

As far as I can think, there isn't any common case where implementing the fix suggested would prevent.

So this fix might end up doing more harm than good (for example: non-const-correct SAMP natives).

**Comment by Y-Less** [comment]
> There probably aren't many scripts which abuse this bug. If there are some, then it's bad code and they should update it.

I've abused this, but I've abused pretty much every bug, and don't really count for consideration since my code is still maintained and I know it's abusive.

> I don't think anything can be done apart from modifying the includes itself.

fixes.inc covers this already.

> I'd vote for that warning being added whether or not the fix I suggest in this issue will be implemented.

Same.

**Comment by samphunter** [comment]
I vote for the warning. 

But I really don't see, why go through the effort of implementing the copying, if code using it is bad anyway.

**Comment by YashasSamaga** [comment]
@samphunter The issue is that array literals (any literal for that matter) should not change its value. It's a constant. In the case outlined in the issue, the values of the literals are being changed which is contrary to the common notion of what a literal is.

```
func(arr[]) { arr[2] = 'Z'; }
main () { 
     func("ABCDEF");
}
```

The problem is that `func` modifies the string literal. Literals are supposed to be immutable but the above code actually changes it.

**bad code?**

If any code assumes that the modifying the array parameter will modify the string literal which was passed, it is bad (in my opinion).

If a function does not mark an array parameter as `const` when it actually does not modify it, it is bad. Writing const-correct code helps the compiler make certain optimizations (like the one I would be describing below).

If the suggestion in this issue is implemented, a copy of the array literal will be made on the heap if and only if the parameter is not marked `const`. This is because we don't want array literals to be modified (because they are literals and are't supposed to be mutable). However, if a function parameter is marked as `const`, we would not have to make a copy of the array literal because it won't be modified. The purpose was copying was to prevent the function from changing the array literal but since it does not change, we can directly pass the array literal safely.

It is not that the code which will cause copies to be created is bad.

**possible solutions:**

There are two ways I can think of to solve the issue:
- trigger an error if an array literal is being passed to a non-const qualified formal parameter
   This is what happens when you try to pass a `const` qualified array to a non-const qualified parameter.
    ```
    new const arr[] = "ABCDEFG";
    func(arr);
    ```
    would give `argument type mismatch (argument 1)`

- make a temporary mutable copy of the array literal on the heap
   if the function modifies the contents of the array, it will modify the copy of the literal on the heap but not the actual literal


The second solution is preferred because people would hate to not have the ability to pass array literals directly to functions.

**Comment by samphunter** [comment]
@YashasSamaga Am I missing something?

The first solution is literally what I voted for, just I wanted to make it a warning instead of error. That is mostly because it does not break anything.

I am saying, that implementing the second option would be redundant, as the only case where it would make a difference would already produce a warning. And for the few people who purposefully ignore/disable the warning, why mess up their code, if they want to change those literals?

**Comment by YashasSamaga** [comment]
```
The first solution is literally what I voted for, just I wanted to make it a warning instead of error. That is mostly because it does not break anything.
```

This would force people to make a copy of the data themselves before passing it to a function to get rid of the warning.

```
I am saying, that implementing the second option would be redundant, as the only case where it would make a difference would already produce a warning. And for the few people who purposefully ignore/disable the warning, why mess up their code, if they want to change those literals?
```

This will make the compiler do the copying process and the compiler can do it more efficiently (can directly place instructions to do the copy; if the user had to do it, they would have to invoke some function to do the copy).

If someone wants the literals to be changed, they should use an array.

It would also be a bad practice to modify literals as they go against the common notion that literals are immutable.

By the way, the compiler makes copies of default argument arrays and references on the heap for the very same reason I am contending for.

> PS: If anything, we could make segfault checks in the interpreter and throw an error, if a script tries to change the code/const data part of the abstract machine. That would cover all the instances, instead of just covering some, but not others, such as vaargs.

We can't modify the server. There is no separate read-only data segment; both read-only and writable-data end up in the same data segment. Hence, it is not possible to tell which parts of the data segment are mutable and which are not. 
As a matter of fact, modifying contents of the code segment is also allowed.

**Comment by samphunter** [comment]
> This would force people to make a copy of the data themselves before passing it to a function to get rid of the warning.

What? Why? You mean if the function is not const correct? They should just make the bloody function const correct, its 5 letters to add... And if the function is supposed to change the string, then they should not give it a literal.

> By the way, the compiler makes copies of default argument arrays and references on the heap for the very same reason I am contending for.

Yes, but that is actually useful. I just can't see, how this could ever be.

**Comment by YashasSamaga** [comment]
> What? Why? You mean if the function is not const correct? They should just make the function const correct, its 5 letters to add... And if the function is supposed to change the string, then they should not give it a literal.

Why wouldn't someone want to pass array literals to a function that modifies it?

> Yes, but that is actually useful. I just can't see, how this could ever be.

The reason why that copy happens and the reason why copy should be made for array literals is exactly the same.

**Comment by samphunter** [comment]
> Why wouldn't someone want to pass array literals to a function that modifies it?

Because you can't read those modifications? What would the point of modifying it would be, if you can;t get the result?

Or do you expect functions, that would both modify the string/array and do something else? What would such a function be?

**Comment by YashasSamaga** [comment]
```
Because you can't read those modifications? What would the point of modifying it would be, if you can't get the result?
```

Even if the array literal was modified, there is no way of getting the literal's value without some assembly. The point is literals are constants which should never be modified. If you try to pass a string literal to a non-const array in C++, the compiler would throw an error<sup>1</sup>. If you indirectly modify a string literal, your program would crash.

1. throwing an error is also an option we have but this would break code

**Comment by samphunter** [comment]
> You actually can read the modifications.

We are talking in the case this proposed modification would be made and a copy was made every time to prevent that behavior.

**Comment by YashasSamaga** [comment]
1. add a warning to inform const incorrect code (already exists but was disabled)
2. add a warning to inform that a literal is being passed to a non-const argument

Is this fine?

**Comment by Daniel-Cortez** [comment]
>add a warning to inform const incorrect code (already exists but was disabled)
add a warning to inform that a literal is being passed to a non-const argument

I'd really like to see this being implemented, but unfortunately some of the SA-MP natives are not const-correct (f.e. `SetTimer` and `SetTimerEx` don't have the `const` specifier for the `funcname` argument) and this would cause false warnings which can only be "fixed" by manually changing function definitions in `a_samp.inc`. And since this will never be fixed* in any of the future SA-MP versions (for well-known reasons), I think this is a big no for implementing those warnings.

<h6>* Actually fixes.inc addresses this problem, but this is just a collection of workarounds, not actual fixes, and it's not a part of any of the SA-MP server redistributions.</h6>

**Comment by Southclaws** [comment]
I was actually considering providing "fixed" standard libraries in [sampctl/samp-stdlib](https://github.com/sampctl/samp-stdlib) which would work fine for all sampctl users but leave other users left with the old versions and the need for workarounds.

Relevant issue: https://github.com/sampctl/samp-stdlib/issues/3

**Comment by Y-Less** [comment]
Question:  How many people using the new compiler, not using sampctl, and with no idea how to update the includes, are we talking about?

**Comment by Southclaws** [comment]
I really should have built in some form of metrics to know at least *how many* sampctl users there are.

**Comment by YashasSamaga** [comment]
We could at least have those warnings as opt-in features.  They will be disabled by default.

**Comment by Daniel-Cortez** [comment]
> I was actually considering providing "fixed" standard libraries in sampctl/samp-stdlib which would work fine for all sampctl users but leave other users left with the old versions and the need for workarounds.

Actually this might be a good idea. We could provide a brief instruction on the compiler release page on how to get and install those modified includes, with or without sampctl.
If someone's not gonna move their lazy butt and fix bugs in their code, the community could do the fixing. At least it's better, than making workarounds in the compiler itself by disabling some warnings by default just because of that bugged code.

**Comment by YashasSamaga** [comment]
For the record (and a correction to the issue title), the implementer guide says:

> For a function that has an array argument with a default value, the compiler allocates space for the default array value on the heap. However, if the array argument (with a default value) is also const, the pawn compiler passes the default array directly (there is no need to make a copy on the heap here, as the function will not attempt to change the array argument and, thereby, overwrite the default value)

**Comment by Y-Less** [comment]
Incorrect warning:

```pawn
_Y_HOOKS_STATIC stock Hooks_GetPreloadLibraries(preloads[][E_CHAIN_HOOK], &precount, size = sizeof (preloads))
{
	P:4("Hooks_GetPreloadLibraries called");
	--size,
	precount = 0;
	new
		entry,
		idx;
	{
		new
			name[32 char],
			addr;
		while ((idx = AMX_GetPublicEntryPrefix(idx, entry, _A<@CO_>)))
		{
			if (precount == size)
			{
				P:E("y_hooks prehook array filled");
				break;
			}
			addr = AMX_Read(entry);
			AMX_ReadString(AMX_Read(entry + 4) + AMX_BASE_ADDRESS + 4, name),
			strunpack(preloads[precount][E_CHAIN_HOOK_NAME], name, 16),
			preloads[precount][E_CHAIN_HOOK_VALUE] = CallFunction(addr),
			++precount;
			if (strlen(name) > 15)
				P:E("Overflow in prehook name \"%s\"", unpack(name));
			// {
				// new buffer[32];
				// strunpack(buffer, name);
				// printf("preload: %s", buffer);
			// }
			// Remove this public from the publics table.  Means that future public
			// function calls will be faster by having a smaller search space.
			Hooks_InvalidateName(entry);
		}
	}
	// Sort the preload libraries.
	{
		new
			tmp[E_CHAIN_HOOK];
		for (entry = precount - 1; entry > 0; --entry)
		{
			for (idx = 0; idx != entry; ++idx)
			{
				if (preloads[idx][E_CHAIN_HOOK_VALUE] > preloads[idx + 1][E_CHAIN_HOOK_VALUE])
				{
					tmp = preloads[idx],
					preloads[idx] = preloads[idx + 1],
					preloads[idx + 1] = tmp;
				}
			}
		}
	}
}
```

```
warning 214: possibly a "const" array argument was intended: "preloads"
```

It definiately wasn't!

**Comment by Y-Less** [comment]
I count 4 writes to `preloads` in that code.  One native call, one slot write, two direct writes.

**Comment by YashasSamaga** [comment]
```
f(arr[]) {

}
main () {
    f("asd");
}
```

The above code triggers unused symbol warning for `arr` but does not suggest for it to be marked as `const`. The argument must be read for the `const` suggestion to appear.

Should `const` qualifier be suggested even if the symbol is unused? It'd be two warnings: unused symbol and `const` suggestion.

As of now the compiler ensures that at most only one of 203, 204 and 214 (in the same order) warning is triggered for a symbol.

**Comment by YashasSamaga** [comment]
I don't understand your argument for public functions. I think `inputtext` should be `const`. The function can be called in two ways:
- called in the script
- called from outside

The `const` for the argument would indicate that the host does not expect the script to modify the argument. Not having `const` would indicate that the script can modify it.

I don't understand what you meant by "indicate that the parameter COULD be modified". This would have no effect on the script. The host allocated memory for the argument and it is modifying it and this is not visible to the script.

I am thinking of it like this:

```
host() { // note: assume this Pawn code is some code in the host expressed in pawn
     new arr[100];
     callback(arr);
    //modify arr because it isn't const here
}

callback(const param[]) { }

```

**Comment by YashasSamaga** [comment]
The `const` suggestion warning has been disabled for `public` functions by marking all array arguments as modified during declaration itself. All public function arguments were marked as read during declaration itself to prevent 203/204. I think marking the arrays as written is also fine. Not sure if the same has to be done for references. There's no bug associated with references but...



What about:

```
public f(arr[]) { }
main() {
  f("abc");
}
```

Should that warn the user that a literal is being passed to a non-const qualified parameter? Since

**Comment by Y-Less** [comment]
Both unused and const warnings would be annoying. If there's a problem with a parameter, one warning is enough (and I'd hope in that case that using `#pragma unused` wouldn't cause the const warning to appear).

**Comment by Y-Less** [comment]
Yes, calling public functions directly should behave like normal function calls, since they are. The only special treatment should be inside publics, and when calling natives.

**Comment by Y-Less** [comment]
Imho this needs to be the highest priority before a new release is made - the code correct code is already in, but incomplete and as it is the compiler at head is totally unusable. It gives hundreds of warnings you simply can't fix because they come from the default includes. That, or const correctness needs reverting.

**Comment by YashasSamaga** [comment]
```
else if ((sym->usage & (uWRITTEN | uPUBLIC | uCONST))==0 && sym->ident==iREFARRAY) {
        int warn = 1;
        symbol* depend = finddepend(sym);
        while (depend != NULL) {
          if ((depend->usage & (uWRITTEN | uPUBLIC | uCONST)) != 0) {
            warn = 0;
            break;
          }
          depend = finddepend(depend);
        } /* while */
```

The bad warnings have been fixed on my local repo. This is a poor fix though (same fix used in destructors too). The actual bug is with #322 but fixing 322 needs a lot of changes at several places.

I think this temporary fix could be used (just like it was used for destructors) and later revert these once 322 is fixed.

**Comment by Daniel-Cortez** [comment]
> We already mentioned natives, but it is annoying. I'd suggest just totally ignoring these warnings for natives that don't use `const`.

Or we could just bundle modified includes from [sampctl/samp-stdlib](https://github.com/sampctl/samp-stdlib) with the compiler binaries (they [became const-correct](https://github.com/sampctl/samp-stdlib/pull/6) since @Southclaws first mentioned them in this conversation, and may have other useful features in the future, like [this one](https://github.com/sampctl/samp-stdlib/pull/9)).
Either that or give up on const-correctness for native functions just because of SA-MP bugs.

**Comment by Zorono** [comment]
it'd be great if it is possible to disable this fix.... as it breaks my scripts's compatibility

**Comment by Y-Less** [comment]
Fix your script then.
